type Comment{
    id: ID
    user_id: Int
    drawing_comment_id: Int
   

}

input CommentInput{
    user_id: Int!
    drawing_comment_id: Int!

}

input CommentUpdateInput{
     user_id: Int
     drawing_comment_id: Int

}