scalar Date
type DrawingComment{
    id: Int
    content: String
    drawing: Drawing                            
     created_at: Date
    updated_at: Date
}


input DrawingCommentInput{
    content: String!
    drawing_id: Int!

}

input DrawingCommentUpdateInput{
     content: String
     drawing_id: Int

}
 