scalar Date
type Drawing{
    id: ID
    name: String
    data: String  
    user: User
    likedByUsers: [User] 
    created_at: Date
    updated_at: Date
}


input DrawingInput{
    name: String!
    data:String!
    user_id: Int!
}

input DrawingUpdateInput{
  
    name: String
    data:String
    user_id: Int

}