scalar Date
type Message {
  id: ID!
  content: String
  user: User
  created_at: Date
  updated_at: Date

}

input MessageInput{
    content: String!
    user_id: ID!
}

input UserUpdateInput {
  content: String
  user_id: Int
}