type Mutation {
    # user
    addUser(input: UserInput!):User
    deleteUser(id: ID!): Boolean
    updateUser(id: ID!, input: UserUpdateInput!): User

    # role

     addRole(input: RoleInput!):Role
     updateRole(id: ID!, input: RoleUpdateInput!): Role
     deleteRole(id: ID!): Boolean

     #message   

    addMessage(input: MessageInput!):Message
    updateMessage(id: ID!, input: UserUpdateInput!): Message
    deleteMessage(id: ID!): Boolean

    # Post
     addPost(input: PostInput!):Post    
     updatePost(id: ID!, input: PostUpdateInput!): Post
     deletePost(id: ID!): Boolean

    # Tpic
    addTopic(input:TopicInput!):Topic
    updateTopic(id: ID!,input:TopicUpdateInput!):Topic
    deleteTopic(id: ID!): Boolean


   # Drawing
     addDrawing(input: DrawingInput):Drawing  
     updateDrawing(id: ID!,input:DrawingUpdateInput) :Drawing
     deleteDrawing(id: ID!): Boolean


    # drawingComment

     addDrawingComment(input: DrawingCommentInput): DrawingComment
     updateDrawingComment(id: ID!,input:DrawingCommentUpdateInput):DrawingComment
     deleteDrawingComment(id: ID!): Boolean


    # Video
     addVideo(input: VideoInput): Video
     updateVideo(id: ID!,input: VideoUpdateInput): Video
     deleteVideo(id: ID!): Boolean

    # Video comment

      addVideoComment(input: VideoCommentInput): VideoComment
      updateVideoComment(id: ID!,input:VideoCommentUpdateInput):VideoComment
      deleteVideoComment(id: ID!): Boolean

  # Video_like
    addVideoLike(input:VideoLikeInput):VideoLike
    deleteVideoLike(id: ID!): Boolean

  #Publish
   addPublishComment(input: PublishInput): Publish
   deletePublishComment(id: ID!): Boolean


  #drawing_like

   addDrawingLike(input:DrawingLikeInput):DrawingLike
   deleteDrawingLike(id: ID!):Boolean

  #  Comment

   addCommentDrawing(input:CommentInput): Comment


  #  loggin

  login(username: String!, password: String!): AuthPayload
}

