type Post{
    id: ID!
    title: String
    content: String
    message: Message

}

input PostInput {
  title: String!
  content: String!
  message_id: Int!
}


input PostUpdateInput {
  title: String
  content: String
  message_id: Int

}
