scalar Date
type Topic{
    id: ID! 
    title: String
    post: Post
    created_at: Date
    updated_at: Date


}


input TopicInput {
  title: String!
  post_id: Int!
}

input TopicUpdateInput {
  title: String
  post_id: Int

}
