scalar Date

type User{
     id: ID
    username: String
    role: Role
    age: Int
    email: String
    gender: String
    interest1: String
    interest2: String
    interest2: String
    likedVideos: [Video]
    publishedComments: [VideoComment]  # Liste de commentaires vidéo que l'utilisateur a laissés.`.
    likedDrawings: [Drawing]
    comments: [DrawingComment]
    created_at: Date
    updated_at: Date

}




input UserInput {
  username: String!
  password: String!
  role_id: Int!
  email: String!
  age: Int!
  gender: String!
  interest1: String
  interest2: String
  interest2: String
}

input UserUpdateInput {
  username: String
  password: String
  role_id: Int
   email: String
  age: Int
  gender: String
  interest1: String
  interest2: String
  interest2: String

}

type AuthPayload {
  token: String
  user: User
}


