type User{
     id: ID! 
    username: String!
    role: Role!
  

}




input UserInput {
  username: String!
  password: String!
  role_id: Int!
}

input UserUpdateInput {
  username: String
  password: String
  role_id: Int

}

