scalar Date
type VideoComment{
    id: Int
    content: String
    video: Video
    usersCommentedOnVideo: [User]  # Liste des utilisateurs qui ont commenté une vidéo
    created_at: Date
    updated_at: Date


}

input VideoCommentInput {
  content: String!
  video_id: Int!
}

input VideoCommentUpdateInput {
  content: String
  video_id: Int

}


